language: node_js
node_js:
  - 15
cache:
  directories:
    - node_modules
script:
  - yarn test:unit
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: script
  edge: true
  script: bash scripts/deploy.sh
  on:
    branch: main